### PR TITLE
feat: AWS Automatic gathering feature, SDK v3 update, Authentication Flow fix

### PR DESCRIPTION
**Pull request by aeppling**

### CODE REVIEW

**Review by estebanmathia — CHANGES_REQUESTED** [review]
Remove KexaAzure in [addOn/awsGathering.service](https://github.com/4urcloud/Kexa/blob/dev/Kexa/services/addOn/awsGathering.service.ts)

**Comment by aeppling** [comment]
fix object azure in aws header

**Comment by aeppling** [comment]
fixed

**Review by estebanmathia — APPROVED** [review]

**Pull request merged**
